export function makeFull5v08() {
  return [
    {
      shortName: 'A1',
      estimations: 0,
      points: 0,
      maxPoints: 50,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'A1.1',
      estimations: 0,
      points: 0,
      maxPoints: 50,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'A1.2',
      estimations: 0,
      points: 0,
      maxPoints: -200,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'A2',
      estimations: 0,
      points: 0,
      maxPoints: 50,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'A2.1',
      estimations: 0,
      points: 0,
      maxPoints: 25,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'A2.2',
      estimations: 0,
      points: 0,
      maxPoints: 25,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'A2.3',
      estimations: 0,
      points: 0,
      maxPoints: -200,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'A3',
      estimations: 0,
      points: 0,
      maxPoints: 50,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'A3.1',
      estimations: 0,
      points: 0,
      maxPoints: 50,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'A3.2',
      estimations: 0,
      points: 0,
      maxPoints: -200,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'A4',
      estimations: 0,
      points: 0,
      maxPoints: 50,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'A4.1',
      estimations: 0,
      points: 0,
      maxPoints: 25,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'A4.2',
      estimations: 0,
      points: 0,
      maxPoints: 25,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'B1',
      estimations: 0,
      points: 0,
      maxPoints: 50,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'B1.1',
      estimations: 0,
      points: 0,
      maxPoints: 16.6666666666667,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'B1.2',
      estimations: 0,
      points: 0,
      maxPoints: 16.6666666666667,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'B1.3',
      estimations: 0,
      points: 0,
      maxPoints: 16.6666666666667,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'B2',
      estimations: 0,
      points: 0,
      maxPoints: 50,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'B2.1',
      estimations: 0,
      points: 0,
      maxPoints: 50,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'B2.2',
      estimations: 0,
      points: 0,
      maxPoints: -200,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'B3',
      estimations: 0,
      points: 0,
      maxPoints: 50,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'B3.1',
      estimations: 0,
      points: 0,
      maxPoints: 25,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'B3.2',
      estimations: 0,
      points: 0,
      maxPoints: 25,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'B3.3',
      estimations: 0,
      points: 0,
      maxPoints: -200,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'B4',
      estimations: 0,
      points: 0,
      maxPoints: 50,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'B4.1',
      estimations: 0,
      points: 0,
      maxPoints: 50,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'B4.2',
      estimations: 0,
      points: 0,
      maxPoints: -200,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'C1',
      estimations: 0,
      points: 0,
      maxPoints: 50,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'C1.1',
      estimations: 0,
      points: 0,
      maxPoints: 16.6666666666667,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'C1.2',
      estimations: 0,
      points: 0,
      maxPoints: 16.6666666666667,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'C1.3',
      estimations: 0,
      points: 0,
      maxPoints: 16.6666666666667,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'C1.4',
      estimations: 0,
      points: 0,
      maxPoints: -200,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'C2',
      estimations: 0,
      points: 0,
      maxPoints: 50,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'C2.1',
      estimations: 0,
      points: 0,
      maxPoints: 16.6666666666667,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'C2.2',
      estimations: 0,
      points: 0,
      maxPoints: 16.6666666666667,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'C2.3',
      estimations: 0,
      points: 0,
      maxPoints: 16.6666666666667,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'C2.4',
      estimations: 0,
      points: 0,
      maxPoints: -200,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'C3',
      estimations: 0,
      points: 0,
      maxPoints: 50,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'C3.1',
      estimations: 0,
      points: 0,
      maxPoints: 16.6666666666667,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'C3.2',
      estimations: 0,
      points: 0,
      maxPoints: 16.6666666666667,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'C3.3',
      estimations: 0,
      points: 0,
      maxPoints: 16.6666666666667,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'C3.4',
      estimations: 0,
      points: 0,
      maxPoints: -200,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'C4',
      estimations: 0,
      points: 0,
      maxPoints: 50,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'C4.1',
      estimations: 0,
      points: 0,
      maxPoints: 16.6666666666667,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'C4.2',
      estimations: 0,
      points: 0,
      maxPoints: 16.6666666666667,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'C4.3',
      estimations: 0,
      points: 0,
      maxPoints: 16.6666666666667,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'C4.4',
      estimations: 0,
      points: 0,
      maxPoints: -200,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'D1',
      estimations: 0,
      points: 0,
      maxPoints: 50,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'D1.1',
      estimations: 0,
      points: 0,
      maxPoints: 25,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'D1.2',
      estimations: 0,
      points: 0,
      maxPoints: 25,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'D1.3',
      estimations: 0,
      points: 0,
      maxPoints: -200,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'D2',
      estimations: 0,
      points: 0,
      maxPoints: 50,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'D2.1',
      estimations: 0,
      points: 0,
      maxPoints: 25,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'D2.2',
      estimations: 0,
      points: 0,
      maxPoints: 25,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'D2.3',
      estimations: 0,
      points: 0,
      maxPoints: -200,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'D3',
      estimations: 0,
      points: 0,
      maxPoints: 50,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'D3.1',
      estimations: 0,
      points: 0,
      maxPoints: 25,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'D3.2',
      estimations: 0,
      points: 0,
      maxPoints: 25,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'D3.3',
      estimations: 0,
      points: 0,
      maxPoints: -200,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'D4',
      estimations: 0,
      points: 0,
      maxPoints: 50,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'D4.1',
      estimations: 0,
      points: 0,
      maxPoints: 25,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'D4.2',
      estimations: 0,
      points: 0,
      maxPoints: 25,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'D4.3',
      estimations: 0,
      points: 0,
      maxPoints: -200,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'E1',
      estimations: 0,
      points: 0,
      maxPoints: 50,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'E1.1',
      estimations: 0,
      points: 0,
      maxPoints: 25,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'E1.2',
      estimations: 0,
      points: 0,
      maxPoints: 25,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'E1.3',
      estimations: 0,
      points: 0,
      maxPoints: -200,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'E2',
      estimations: 0,
      points: 0,
      maxPoints: 50,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'E2.1',
      estimations: 0,
      points: 0,
      maxPoints: 25,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'E2.2',
      estimations: 0,
      points: 0,
      maxPoints: 25,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'E2.3',
      estimations: 0,
      points: 0,
      maxPoints: -200,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'E2.4',
      estimations: 0,
      points: 0,
      maxPoints: -200,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'E3',
      estimations: 0,
      points: 0,
      maxPoints: 50,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'E3.1',
      estimations: 0,
      points: 0,
      maxPoints: 25,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'E3.2',
      estimations: 0,
      points: 0,
      maxPoints: 25,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'E3.3',
      estimations: 0,
      points: 0,
      maxPoints: -200,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'E4',
      estimations: 0,
      points: 0,
      maxPoints: 50,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'E4.1',
      estimations: 0,
      points: 0,
      maxPoints: 25,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'E4.2',
      estimations: 0,
      points: 0,
      maxPoints: 25,
      weight: 1,
      isWeightSelectedByUser: false,
    },
    {
      shortName: 'E4.3',
      estimations: 0,
      points: 0,
      maxPoints: -200,
      weight: 1,
      isWeightSelectedByUser: false,
    },
  ];
}
