name: Build docker image when pushed to main
on:
  push:
    branches: ['main']


jobs:
  checks:
    uses: ./.github/workflows/check-workflow.yml
    with:
      node-version: 18.7.0
    secrets: inherit

  build:
    runs-on: ubuntu-latest
    needs:
      - checks
    steps:
      - uses: actions/checkout@v5
      - name: Build and tag image
        run: |
          docker build -t ${{vars.IMAGE_NAME}}:${{ github.sha }} -t ${{vars.IMAGE_NAME}}:latest .

      - name: Login to econgood repo
        run: |
          docker login -u econgood -p ${{ secrets.ECONGOOD_CONTAINER_REGISTRY }}

      - name: Push the image
        run: |
          docker push ${{vars.IMAGE_NAME}} --all-tags


