name: Build docker image when pushed to main
on:
  push:
    branches: ['main']

jobs:
  checks:
    uses: ./.github/workflows/check-workflow.yml
    with:
      node-version: 18.7.0
    secrets: inherit

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Build and tag image
        run: |
          docker build -t econgood/balance-sheet-api:${{ github.sha }} -t econgood/balance-sheet-api:latest .

    
