name: Deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'test'
        type: choice
        options:
          - test
          - prod

env:
  NODE_VERSION: 18.7.0

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh-keyscan ${{ vars.HOST_URL }} >> ~/.ssh/known_hosts
          ssh root@${{ vars.HOST_URL }} "docker login -u econgood -p ${{ secrets.ECONGOOD_CONTAINER_REGISTRY }} && cd ${{vars.APP_DIR}} && docker compose pull && docker compose up -d"
 
